NEW_LINE_CHARACTER = "&"

PLAYER_BASE_PV = 10
PLAYER_BASE_ATTACK = 5 # Dégâts émis
PLAYER_BASE_RESISTANCE = 0 # Dêgats réduits de 0% de l'attaque de base
PLAYER_LEVEL_AUGMENTATION_PV = 7
PLAYER_LEVEL_AUGMENTATION_ATTACK = 6
PLAYER_LEVEL_AUGMENTATION_RESISTANCE = 0.1

MONSTER_BASE_PV = 10
MONSTER_BASE_PV_RANGE = 10 # Choix aléatoire avec distance maximale MONSTER_BASE_PV_RANGE/2
MONSTER_BASE_ATTACK = 2
MONSTER_BASE_ATTACK_RANGE = 6
MONSTER_BASE_RESISTANCE = 0.1
MONSTER_BASE_RESISTANCE_RANGE = 0.2
MONSTER_LEVEL_AUGMENTATION_PV = 8
MONSTER_LEVEL_AUGMENTATION_ATTACK = 5
MONSTER_LEVEL_AUGMENTATION_RESISTANCE = 0.1

BASE_EXP_REWARD = 10
BASE_EXP_REWARD_RANGE = 10 # Choix aléatoire entre BASE_EXP_REWARD - BASE_EXP_REWARD/2 et BASE_EXP_REWARD + BASE_EXP_REWARD/2
EXP_REWARD_LEVEL_AUGMENTATION_COEFF = 1.3 # Exp = BASE_EXP_REWARD * (EXP_REWARD_LEVEL_AUGMNTATION_COEFF ** Level)

BASE_EXP_LEVEL_UP = 30 # Exp nécéssaire pour augmenter de niveau
BASE_EXP_LEVEL_UP_AUGMENTATION_COEFF = 1.3